primer:
  926R : "AAACTYAAAKRAATTGRCGG" #reverse complement
  806RB : "ATTAGAWACCCBNGTAGTCC" #reverse complement
  515Y : "GTGYCAGCMGCCGCGGTAA"
  V4F : "CCAGCASCYGCGGTAATTCC"
  V4RB : "YYRATCAAGAACGAAAGT" #reverse complement
  341F : "CCTACGGGNGGCWGCAG" #2-mismatch already present in Sulfolobus reference SSU rRNA positions 367, 371 so not a truly Prokaryotic primer
  785R : "GGATTAGATACCCBDGTAGTC" #reverse complement, perfect match to reference
  27F : "AGRGTTTGATYMTGGCTCAG"
  338R : "ACWCCTACGGGWGGCWGCA" #reverse complement

groups:
  EUK : EUK
  ARCH : ARCH
  BACT-NON-CYANO : BACT-NON-CYANO
  BACT-CYANO : BACT-CYANO

mismatches:
  0-mismatch : 0
  1-mismatch : 1
  2-mismatch : 2

primerROI:
  EUK:
    515Y: [562,580]
    806RB : [0, 0]
    926R: [1131,1150]
    V4F : [565, 584]
    V4RB : [964, 981]
    341F : [0, 0]
    785R : [0, 0]
    27F : [0, 0]
    338R : [0, 0]

  ARCH:
    515Y: [486,504]
    806RB : [758, 777]
    926R: [882,901]
    V4F : [0, 0]
    V4RB : [0, 0]
    341F : [358, 374]
    785R : [756, 776]
    27F : [0, 0]
    338R : [0, 0]

  BACT-NON-CYANO:
    515Y: [515,533]
    806RB : [787, 806]
    926R: [907, 926]
    V4F : [0, 0]
    V4RB :  [0, 0]
    341F : [341, 357]
    785R : [785, 805]
    27F : [6, 27]
    338R : [338, 356]

  BACT-CYANO:
    515Y: [494, 512]
    806RB : [766, 785]
    926R: [867, 906]
    V4F : [0, 0]
    V4RB : [0, 0]
    341F : [345, 361]
    785R : [764, 784]
    27F : [18, 37]
    338R : [342, 360]

samples:
