primer:
  926R : "AAACTYAAAKRAATTGRCGG" #reverse complement
  806RB : "ATTAGAWACCCBNGTAGTCC" #reverse complement
  515Y : "GTGYCAGCMGCCGCGGTAA"
  V4F : "CCAGCASCYGCGGTAATTCC"
  V4RB : "YYRATCAAGAACGAAAGT" #reverse complement

groups:
  EUK : EUK
  ARCH : ARCH
  BACT-NON-CYANO : BACT-NON-CYANO
  BACT-CYANO : BACT-CYANO

mismatches:
  0-mismatch : 0
  1-mismatch : 1
  2-mismatch : 2

primerROI:
  EUK:
    515Y: [562,580]
    926R: [1131,1150]
    V4F : [565, 584]
    V4RB :  [964, 981]
    806RB : [0, 0]
  ARCH:
    515Y: [486,504]
    926R: [882,901]
    V4F : [0, 0]
    V4RB :  [0, 0]
    806RB : [758, 777]
  BACT-NON-CYANO:
    515Y: [515,533]
    926R: [907, 926]
    V4F : [0, 0]
    V4RB :  [0, 0]
    806RB : [787, 806]
  BACT-CYANO:
    515Y: [491,509]
    926R: [864,903]
    V4F : [0, 0]
    V4RB :  [0, 0]
    806RB : [763, 782]
    
samples:
